name: Push to AWS s3 staging
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  push-to-s3-staging:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN_STAGING }}
          aws-region: eu-west-1

      # - name: Copy files using script
      #   env:
      #     BUCKET_STAGING: ${{ secrets.BUCKET_STAGING }}
      #     WORKSPACE: ${{ github.workspace }}
      #   run: ./bin/upload
      
      - name: Post S3 website URL as a comment
        env:
          BUCKET_STAGING: ${{ secrets.BUCKET_STAGING }}
        run: |
          curl \
            -X POST \
            ${{ github.event.issue.comments_url }} \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "Content uploaded!\nURL: http://${{ secrets.BUCKET_STAGING }}/.s3-website-eu-west-1.amazonaws.com/" }'