# push repo content when PRs are closed and merged

name: Push to AWS s3 production
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'master'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN_PRODUCTION }}
          aws-region: eu-west-1

      - name: Copy files using script
        env:
          BUCKET_PRODUCTION: ${{ secrets.BUCKET_PRODUCTION }}
          WORKSPACE: ${{ github.workspace }}
        run: ./bin/upload
      
      - name: Create comment with prod website URL
        uses: peter-evans/commit-comment@v1
        with:
          token: ${{ secrets.GH_ACTIONS_PAT }}
          repository: ${{ github.repository }}
          sha: ${{ github.event.pull_request.head.sha }}
          body: |
            Upload to [prod](http://bosmans-and-beyond.s3-website-eu-west-1.amazonaws.com) completed.
